services:
  cinemaflix.api:
    image: cinemaflix.api
    build:
      context: .
      dockerfile: src/CinemaFlix.Api/Dockerfile

  postgres:
    image: postgres
    ports:
       - "5432:5432"
    environment:
       POSTGRES_PASSWORD: postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
     postgres_data:
